#!/bin/bash
set -e

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd "${dir}"

# Images ordered to reflect dependencies.
files="
robolab_melodic
"
for f in robolab_melodic; do
    sudo rm -f "${f}.simg"
    sudo singularity build "${f}.simg" "${f}.txt" 2>&1 | tee "${f}.log" \
        && sudo chown ${USER}:${USER} "${f}.simg"
done
